server:
  port: 8081

spring:
  application:
    name: travel-agent-spring-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:3b
        temperature: 0.2
        num-predict: 600
  datasource:
    url: jdbc:postgresql://localhost:5432/travel_agent
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

travel:
  tavily:
    api-url: https://api.tavily.com/search
    api-key: ${TAVILY_API_KEY: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}
  aviation:
    api-url: https://api.aviationstack.com/v1
    api-key: ${AVIATIONSTACK_API_KEY:eba3c6a8c055297e535ff7f9385b4e7c}

logging:
  level:
    com.example.travel: INFO
    org.springframework.ai: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
